#import "./token"
#import "./reward"
#import "./vault"
#import "./transaction"

fragment PoolFields on Pool {
  id
  timestamp
  transaction {
    ...TransactionFields
  }
  type
  vault {
    ...VaultFields
  }
  rewardTokens {
    ...TokenFields
  }
  rewards {
    ...RewardFields
  }
}
