name: 'coverage'
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm i && npm run test:coverage
