name: 'coverage'
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.messaage, '[skip ci]')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      -name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test:coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-dashboard
          fail_ci_if_error: true
          verbose: true