name: 'coverage'
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-dashboard
          fail_ci_if_error: true
          verbose: true